name: izzat
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  auto_route: ^5.0.4
  
  awesome_snackbar_content: ^0.1.0
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dropdown_button2: ^1.9.2
  flutter:
    sdk: flutter
  flutter_animated_button: ^2.0.3
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.6.2
  flutter_web_plugins:
    sdk: flutter
  flutterwebapp_reload_detector: ^0.0.1
  get: 4.6.5
  getwidget: ^3.0.1
  go_router: ^6.0.3
  google_fonts: ^3.0.1
  http: ^0.13.5
  responsive_grid: ^2.1.0
  shared_preferences: ^2.0.17
  sizer: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.3
  build_runner:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
